import type { Study } from '~/types/study';

const studies: Study[] = [
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 7777777777777,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 1,
    menu: '스터디',
    title: '평일 매일 아침 8시~정오 12시 화면공유 온라인 모각코 인원충원중',
    content: '내용1111',
    proceed: ['온라인'],
    position: ['전체'],
    technologyStack: ['JAVA', 'JS', 'SPRING'],
    startDate: '2023.09.09',
    endDate: '2024.09.09',
    username: '코피',
    hits: 2000,
    commentsCount: 1079,
    recruitmentCount: 10,
  },
  {
    studyId: 2,
    menu: '스터디',
    title: 'IT(비 개발, 개발) 기술력 향상 우리 스터디 하나면 끄읕!',
    content: '내용2222',
    proceed: ['온/오프라인'],
    position: ['프론트엔드', '백엔드'],
    technologyStack: ['JAVA', 'JS', 'TS', 'REACT', 'SPRING'],
    startDate: '2023.10.10',
    endDate: '2024.10.10',
    username: '코드모락',
    hits: 25435,
    commentsCount: 245345,
    recruitmentCount: 0,
  },
  {
    studyId: 3,
    menu: '스터디',
    title: 'AI 시장의 폭발적인 성장, 기회는 미리 준비한 자의 것!',
    content: '내용3333',
    proceed: ['온/오프라인'],
    position: ['전체'],
    technologyStack: ['PYTHON'],
    startDate: '2023.11.11',
    endDate: '2024.11.11',
    username: '무한루프',
    hits: 123,
    commentsCount: 4526,
    recruitmentCount: 0,
  },
  {
    studyId: 4,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 5,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
  {
    studyId: 6,
    menu: '스터디',
    title: 'JAVA/Spring 백엔드 취업 메이트',
    content: '내용44444',
    proceed: ['오프라인'],
    position: ['백엔드'],
    technologyStack: ['JAVA', 'SPRING'],
    startDate: '2023.12.12',
    endDate: '2024.12.12',
    username: '반복문',
    hits: 235,
    commentsCount: 875,
    recruitmentCount: 4,
  },
];
export default studies;
